fauna/faunadb-go

faunadb/client_test.go
faunadb/query.go
faunadb/serialization_test.go

Closes: https://github.com/faunadb/sales-engineering/issues/393

Removing count function

---

.travis.yml
codecov.yml

Closes: https://github.com/faunadb/faunadb-go/pull/28

Adding code coverage

---

faunadb/benchmark_test.go
faunadb/deserialization_test.go
faunadb/errors_test.go

Reported by https://goreportcard.com/report/github.com/faunadb/faunadb-go while dealing with https://github.com/faunadb/sales-engineering/issues/383.

Simplify some statements

---

faunadb/decode.go
faunadb/deserialization_test.go
faunadb/field_test.go
faunadb/path.go
faunadb/serialization_test.go

I'm looking at the coverage report and fixing a few missing branches. This is still a WIP. I'll let you know once it's ready for review.

Testing missing branches

---

faunadb/client_test.go
faunadb/errors.go
faunadb/errors_test.go
faunadb/faunadb_test.go

Closes: https://github.com/faunadb/sales-engineering/issues/451

Implementing permission denied error

---

faunadb/deserialization_test.go
faunadb/reflect.go
faunadb/serialization_test.go

I realised that we missing this case.

Add tag to ignore a struct field

---

faunadb/client.go
faunadb/decode.go
faunadb/doc.go
faunadb/expr.go
faunadb/field.go
faunadb/path.go
faunadb/query.go
faunadb/values.go

LMK if you see anything obviously wrong.

Cleanup docstrings a bit.

---

faunadb/client.go
faunadb/client_test.go
faunadb/decode.go
faunadb/doc.go
faunadb/expr.go
faunadb/field.go
faunadb/path.go
faunadb/query.go
faunadb/serialization_test.go
faunadb/values.go

will only work after https://github.com/fauna/faunadb-go/pull/46 gets merged

Adds singleton and events functions

---

faunadb/values.go

I missed a few the first time.

Correct spelling of 'traversable', part two.

---

.travis.yml
CHANGELOG.md
README.md

Follow up on #84 without fix to #77

Release v2.11.0

---

faunadb/client_test.go
faunadb/query.go

Adds 
- IsNumber
- IsDouble
- IsInteger
- IsBoolean
- IsNull
- IsBytes
- IsTimestamp
- IsDate
- IsString
- IsArray
- IsObject
- IsRef
- IsSet
- IsDoc
- IsLambda
- IsCollection
- IsDatabase
- IsIndex
- IsFunction
- IsKey
- IsToken
- IsCredentials
- IsRole

ENG-1610: Add type check functions

---

README.md

I found the tests, way more useful than your documentation.
import (
f "github.com/fauna/faunadb-go/faunadb"
)
var (
ref  = f.ObjKey("ref")
)
func controller(){
var refrenceID f.RefV
result.At(ref).Get(&refrenceID)
}
Only in your documentation did I find a working field example of this simple yet useful feature.

Updating with another form of help for users

---

faunadb/encode.go
faunadb/serialization_test.go

Follow up to #88 
References: 
https://stackoverflow.com/questions/13476349/check-for-nil-and-nil-interface-in-go

DRV-25: Fix wrap() to handle nil as expr

---

CHANGELOG.md
README.md

- Add client specified query timeout
- Update Ref() to take two arguments
- Handle nil as NullV{}
- Add type check functions:
IsEmpty(), IsNonEmpty(), IsNumber(), IsDouble(), IsInteger()
IsBoolean(), IsNull(), IsBytes(), IsTimestamp(), IsDate()
IsString(), IsArray(), IsObject(), IsRef(), IsSet(), IsDoc()
IsLambda(), IsCollection(), IsDatabase(), IsIndex(), IsFunction()
IsKey(), IsToken(), IsCredentials(), IsRole()

Release v2.12.0

---

CHANGELOG.md
README.md

Changelog:
- Make base64 encoding of secret match other drivers.

Release v2.12.1

---

faunadb/client.go
faunadb/client_test.go
faunadb/functions_collections.go
faunadb/serialization_test.go
faunadb/strconv_test.go

DRV-103: Add reverse fn

---

faunadb/client.go
faunadb/client_test.go
faunadb/functions_collections.go
faunadb/serialization_test.go
faunadb/strconv_test.go

- Deprecates Contains()
- Adds ContainsField, ContainsValue, ContainsPath

DRV-187: Refactor contains into family of functions

---

faunadb/client_test.go
faunadb/functions_strings.go
faunadb/query.go
faunadb/serialization_test.go
faunadb/strconv.go
faunadb/strconv_test.go

- Make Number parameter optional

DRV-262: Fix Repeat() signature

---

.circleci/config.yml

Added public fauna image to circleci config file

---

faunadb/client.go
faunadb/client_test.go
faunadb/functions_ref.go
faunadb/functions_write.go
faunadb/serialization_test.go

- CreateAccessProvider | AccessProvider | AccessProvides
- added serialization | client tests
- changed api version from 3 to 4 in request

DRV-182: Added access provider functions

---

faunadb/client.go

DRV-587: added Bearer support header

---

.circleci/config.yml
CHANGELOG.md
README.md
faunadb/client_test.go
faunadb/example_test.go
faunadb/functions_ref.go
faunadb/serialization_test.go
faunadb/stream_test.go
go.mod

The following functions were added:
- CurrentIdentity
- CurrentToken
- HasCurrentIdentity
- HasCurrentToken

Drv 599 complete 3rd party auth support

---

faunadb/client_test.go
faunadb/perf_test.go

See [OSS-675](https://faunadb.atlassian.net/browse/OSS-675).

OSS-675: Added tests for parallel testing

---

faunadb/client_test.go
faunadb/errors.go
faunadb/errors_test.go
faunadb/stream_test.go

Implemented a new exception hierarchy
https://faunadb.atlassian.net/browse/OSS-866

feat(OSS-866): Implemented new driver exception hierarchy

---

faunadb/stream.go
faunadb/stream_events.go
faunadb/stream_test.go

Changes:
* New set event type;
* New index field constant;
* Test case.

ENG-3044: Introduce set streaming support

---

faunadb/client.go
faunadb/stream.go
faunadb/stream_events.go
faunadb/stream_test.go

Adding `main` branch changes to v5

introduce set streaming support (#163)
