LICENSE, README.md, faunadb/client_test.go, faunadb/example_test.go
Bumps copyright date and updates github links for the org change.
Part of https://github.com/fauna/sales-engineering/issues/525.
=> Update driver info

.travis.yml, README.md, faunadb/benchmark_test.go
Go 1.8 was released 16th February: https://blog.golang.org/go1.8
I didn't add a change log because there was no change at all. The code is already compliant with 1.8 version.
=> Support go 1.8

faunadb/client_test.go
Handles a non-sane situation where this test can be running without a valid server key, which previously resulted in the tests crashing.
=> Check for errors after creating test key

Makefile
Dunno why I thought this was needed.
Updating now so the makefiles are all inline across the drivers (that will have docker images).
=> Remove unneeded override from Makefile

faunadb/client_test.go, faunadb/query.go, faunadb/serialization_test.go
This PR was repurposed, instead of adding a sugar for `select(...,all=true)` now it calls the function `select_all` directly
=> Adds support to select_all function

faunadb/query.go
We can maintain binary compatibility with `NextID()`, but only support the newer query language feature.
=> NextID() should not emit a deprecated function call.

faunadb/deserialization_test.go, faunadb/json.go
Because we were not consuming the closing character of the `@query` type, it was making the parser finish the parsing of `resource` property and thus moving the properties `permissions` and `role` to its parent
```json
{
"resource": {
"ref": { "@ref": "functions/create_entry3" },
"class": { "@ref": "functions" },
"ts": 1528404902084061,
"name": "create_entry3",
"body": {
"@query": {
"lambda": [ "title", "body" ],
"expr": {
"create": { "class": "posts" },
"params": {
"object": {
"title": { "var": "title" },
"body": { "var": "body" }
}
}
}
}
},
"permissions": { "call": "public" },
"role": "server"
}
}
```
so it was being parsed as
```json
{
"resource": {
"ref": { "@ref": "functions/create_entry3" },
"class": { "@ref": "functions" },
"ts": 1528404902084061,
"name": "create_entry3",
"body": { …
```
=> Fix parsing of @query types nested in objects

README.md, faunadb/encode.go, faunadb/encode_test.go
IIRC, a customer request.
While I was in there, I also wrote a test that runs through all the cases of `wrap()`, since it seemed weird to only have a repo case for `reflect.Array` and nothing else :)
Tested via:
```
➜  faunadb-go git:(nathan/ENG-160_array_encoding) FAUNA_ENDPOINT=http://localhost:8443 FAUNA_ROOT_KEY=secret go test ./... 
ok      github.com/fauna/faunadb-go/faunadb     3.316s 
```
=> ENG-160 : Allow encoding of arrays, not just slices

faunadb/client_test.go, faunadb/encode.go, faunadb/serialization_test.go
The Go driver accepts the native `true` and `false`, but not `nil`.
=> DRV-25: Accept nil as Null() expr

README.md, faunadb/client_test.go, faunadb/query.go
Makes it possible to use
```go
f.Ref(f.Collection("user"), "42")
```
=> DRV-24: Make Ref() accept 2 args

faunadb/client.go
> Response error 500. Errors: [](internal server error): java.lang.IllegalArgumentException: Illegal base64 character 3a
Follow the same pattern as Java and JS about the encoding of the secret.
Java:
https://github.com/fauna/faunadb-jvm/blob/d087a89b27875b662fbd5ca648bea3a3b626254f/faunadb-common/src/main/java/com/faunadb/common/Connection.java#L477-L484
JS:
https://github.com/fauna/faunadb-js/blob/08a45a84fa20c511ef196b973f9a8a8866e6ed27/src/Client.js#L260
=> fix: illegal character.

faunadb/expr.go, faunadb/functions_auth.go, faunadb/functions_basic.go, faunadb/functions_collections.go, faunadb/functions_datetime.go, faunadb/functions_logic.go, faunadb/functions_math.go, faunadb/functions_read.go, faunadb/functions_ref.go, faunadb/functions_sets.go, faunadb/functions_strings.go, faunadb/functions_types.go, faunadb/functions_write.go, faunadb/query.go, faunadb/serialization_test.go, faunadb/strconv.go, faunadb/strconv_test.go, faunadb/values.go
Go driver's string representations for various types is unfriendly and uninformative. This makes output friendlier.
=> DRV-27: Implement String() for Expr, showing query

faunadb/client.go, faunadb/deserialization_test.go
- No tests in client_test were added since lambda field in QueryV is not exported and `client_test.go` is in faunadb_test package
- Added a deserialization test
See #108
=> DRV-215: Tests for versioned queries

faunadb/client.go
This PR applied new set of headers based on environment/partner information.
- X-Runtime-Environment
name of runtime env (ex: Netlify, Vercel, etc..) or Unknown for an environment that can't be recognizable
- X-Runtime-Environment-OS
Name of OS (ex: darwin, linux)
For more detailes see - [DRV-489](https://faunadb.atlassian.net/browse/DRV-489).
=> DRV-489: Added runtime env/partner info to headers

README.md
I was trying to look at the driver's doc but found the same thing reported in issue #125 . It looks like that's because the module is defined as [github.com/fauna/faunadb-go/**v3**](https://github.com/fauna/faunadb-go/blob/master/go.mod#L1) so the [old link](https://pkg.go.dev/github.com/fauna/faunadb-go?tab=overview) doesn't resolve to the correct module documentation.  
I believe the correct link to the v3 (latest) release is https://pkg.go.dev/github.com/fauna/faunadb-go/v3.
https://faunadb.atlassian.net/browse/DRV-530
=> DRV-520: Fix Godoc Link to Use the Correct Module Path

faunadb/client.go
Notes: see [issue](https://faunadb.atlassian.net/browse/DRV-577).
Streaming application are interrupted by timeout in HttpClient.
This PR moved this timeout to context.withTimeout for all non-streaming requests.
=> DRV-577: moved request timeout to context.withTimeout

faunadb/decode.go, faunadb/deserialization_test.go, faunadb/reflect.go, faunadb/serialization_test.go, faunadb/tags.go
This commit fixes [#123](https://github.com/fauna/faunadb-go/issues/123) and enables discarding zero valued fields when saving structs that are tagged with omitempty.
```go
func TestSerializeStructWithOmitEmptyTags(t *testing.T) {
type TestStruct struct{}
type OmitStruct struct {
Name           string      `fauna:"name,omitempty"`
Age            int         `fauna:"age,omitempty"`
Payment        float64     `fauna:"payment,omitempty"`
AgePointer     *int        `fauna:"agePointer,omitempty"`
PaymentPointer *float64    `fauna:"paymentPointer,omitempty"`
Struct         *TestStruct `fauna:"struct,omitempty"`
}
x := 10
y := 42.42
z := TestStruct{}
tests := []struct {
name string
expr Expr
want string
}{
{
name: "Empty Int",
expr: Obj{"data": OmitStruct{Name: "John", Age: 0}},
want: …
```
=> DRV-368: added support for omitempty field tag

faunadb/client_test.go, faunadb/functions_read.go, faunadb/query.go, faunadb/serialization_test.go
Introduce `cursor` parameter to provide `before/after` cursors.
E.g.:
```go
res = s.query(
f.Paginate(
f.Documents(f.Collection(collectionName)),
f.Size(3),
f.Cursor(nil),
))
```
```go
res = s.query(
f.Paginate(
f.Documents(f.Collection(paginateColName)),
f.Cursor(f.Obj{"before": f.Ref(...)}),
))
```
=> DRV-15: add support for paginate cursor object

faunadb/errors.go, faunadb/errors_test.go, faunadb/stream_test.go
Based on https://github.com/fauna/faunadb-go/issues/83 and https://faunadb.atlassian.net/browse/DRV-567.
When error occurs in web-shell user observes the following error output:
```json
Error: [
{
"position": [],
"code": "call error",
"description": "Calling the function resulted in an error.",
"cause": [
{
"position": ["expr"],
"code": "invalid ref",
"description": "Ref refers to undefined index 'user_ref_by_username'"
}
]
}
]
```
the same error output in go driver looks like this:
`Response error 400. Errors: [](call error): Calling the function resulted in an error.`
which means that go driver does not display cause field.
=> DRV-567: query error output should be consistent with fauna web shell

faunadb/client.go
- User are able to provide custom headers via FaunaClient:
```go
dbClient = f.NewFaunaClient(sec, f.Headers(map[string]string{"X-Fauna-Source": "Console"}))
```
=> DRV-571: create way to identify Fauna tooling in drivers

.circleci/config.yml, faunadb/client.go, faunadb/client_test.go, faunadb/stream_test.go
This change creates new QueryConfigs that can be used to set the Traceparent header and X-Fauna-Tags header. Simple tests exercise the new headers and assert that they are returned in the response.
=> Adding tag and traceparent functionality with simple tests.
